name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.zig"
      - ".github/workflows/ci.yml"
  push:
    branches:
      - main
    paths:
      - "**.zig"
      - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Check formatting
        run: zig fmt --check .

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test --summary all
